<?xml version="1.0"?>
<package format="3">
  <name>agri_chassis_serial</name>
  <version>0.1.0</version>
  <description>Shared Modbus RTU implementation for chassis ROS 2 nodes.</description>
  <maintainer email="czb@todo.todo">czb</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>python3-pymodbus</exec_depend>
  <exec_depend>python3-serial</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
