<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>chassis_control</name>
  <version>0.0.1</version>
  <description>Chassis control for tracked vehicle with RS485 communication</description>
  <maintainer email="czb@example.com">czb</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>geometry_msgs</depend>
  <depend>trunk_interfaces</depend>
  <depend>agri_chassis_serial</depend>
  
  <!-- 升级版串口通信依赖 -->
  <exec_depend>python3-pymodbus</exec_depend>
  <exec_depend>python3-serial</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
